from __future__ import annotations

from pathlib import Path

import numpy as np

from sb3_tools import save_gif, train_sb3


ROOT = Path(__file__).resolve().parent

SPACE = {
    "title": {"en": "ViZDoom CPU Training Arena", "zh": "ViZDoom CPU 在线训练场"},
    "description": {
        "en": "Train visual agents inside real Doom-engine scenarios, follow every checkpoint, and watch the learned policy replay generated by this CPU run.",
        "zh": "在真实 Doom 引擎场景中训练视觉智能体，观察每次评估，并播放本次 CPU 训练生成的策略回放。",
    },
    "badge": "EXPERIMENT 02 · FPS",
    "training_guide": {
        "success": {"en": "The final mean reward should exceed early checkpoints, and the replay should aim, survive, or reach the selected objective more reliably. Training complete alone only confirms the pipeline finished.", "zh": "最终平均奖励应高于早期检查点，回放中应能更稳定地瞄准、生存或完成所选目标；仅显示“训练完成”只表示流程正常结束。"},
        "preview": {"en": "The opening animation introduces the scenario. After completion, Preview is replaced by the Doom replay generated by this run; inspect movement, aiming, firing, health, and survival.", "zh": "初始动画用于介绍场景；训练结束后，Preview 会替换为本次运行生成的 Doom 回放，请观察移动、瞄准、射击、生命值和生存表现。"},
        "time": {"en": "A short smoke run takes 1–4 minutes. The recommended visual DQN baselines usually need about 10–60 minutes on CPU, depending on the scenario.", "zh": "短流程验证通常需要 1–4 分钟；推荐的视觉 DQN 学习配方在 CPU 上通常需要约 10–60 分钟，具体取决于场景。"},
    },
    "course_url": "https://walkinglabs.github.io/hands-on-modern-rl/chapter07_dqn/visual-game-projects",
    "source_url": "https://modelscope.cn/studios/walkinglab/hands-on-modern-rl-experiment02-vizdoom/file/view/master/space_runtime.py",
    "notebook_url": "https://modelscope.cn/notebook/share/github/walkinglabs/hands-on-modern-rl/blob/main/"
    "code/online-experiments/hands-on-modern-rl-experiment02-vizdoom.ipynb",
}


def task(key, title, environment, description, action, preview, budget, max_steps):
    return {
        "key": key,
        "title": {"en": title, "zh": title},
        "environment": environment,
        "description": description,
        "observation": {"en": "RGB first-person frames", "zh": "第一人称 RGB 画面"},
        "action": action,
        "algorithm": "DQN",
        "policy": "CnnPolicy",
        "preview": preview,
        "budget": budget,
        "learning_rate": (1e-5, 0.002, 0.00025, 1e-5),
        "gamma": (0.8, 1.0, 0.99, 0.005),
        "epsilon": (0.01, 1.0, 0.35, 0.01),
        "checkpoints": 6,
        "max_steps": max_steps,
        "baseline_name": "ViZDoom DQN learning baseline",
        "baseline_time": {"en": "about 10–60 minutes on CPU", "zh": "CPU 上约 10–60 分钟"},
        "baseline_outcome": {"en": "Evaluation reward improves and the replay shoots, survives, or reaches the objective more reliably.", "zh": "评估奖励提高，回放中能更稳定地射击、生存或到达目标。"},
    }


TASKS = [
    task("basic", "Basic Aim & Shoot", "VizdoomBasic-v1", {"en": "Move left or right, line up one target, and fire before timeout.", "zh": "左右移动完成瞄准，在超时前击中目标。"}, {"en": "Left / right / attack", "zh": "左移、右移、射击"}, "assets/vizdoom-basic.gif", (2_000, 500_000, 120_000, 2_000), 350),
    task("defend-center", "Defend the Center", "VizdoomDefendCenter-v1", {"en": "Rotate, manage ammunition, and stop enemies approaching from every direction.", "zh": "转向、管理弹药并阻止敌人从四周靠近。"}, {"en": "Turn / attack", "zh": "转向、射击"}, "assets/vizdoom-defend-center.gif", (5_000, 1_000_000, 300_000, 5_000), 1_200),
    task("health-gathering", "Health Gathering", "VizdoomHealthGathering-v1", {"en": "Navigate over damaging terrain and collect medkits to survive longer.", "zh": "在持续受伤的地面上导航，收集医疗包延长生存时间。"}, {"en": "Turn / move forward", "zh": "转向、前进"}, "assets/vizdoom-health-gathering.gif", (5_000, 1_000_000, 300_000, 5_000), 1_200),
    task("my-way-home", "My Way Home", "VizdoomMyWayHome-v1", {"en": "Explore colored rooms and learn a route through the first-person maze.", "zh": "探索不同颜色的房间，学习第一人称迷宫路线。"}, {"en": "Turn / move forward", "zh": "转向、前进"}, "assets/vizdoom-my-way-home.gif", (5_000, 1_000_000, 300_000, 5_000), 1_500),
    task("deadly-corridor", "Deadly Corridor", "VizdoomDeadlyCorridor-v1", {"en": "Advance toward the vest while fighting enemies placed along the corridor.", "zh": "沿走廊前进，在对抗敌人的同时到达护甲。"}, {"en": "Move / turn / attack", "zh": "移动、转向、射击"}, "assets/vizdoom-deadly-corridor.png", (10_000, 2_000_000, 600_000, 10_000), 2_100),
    task("deathmatch", "CPU Deathmatch", "VizdoomDeathmatch-v1", {"en": "Learn movement, weapon selection, resource collection, and combat in one arena.", "zh": "在竞技场中学习移动、武器选择、资源收集和战斗。"}, {"en": "Discrete combat action set", "zh": "离散战斗动作集合"}, "assets/vizdoom-deathmatch.png", (10_000, 3_000_000, 1_000_000, 10_000), 2_000),
]


def runtime_status():
    try:
        import gymnasium as gym
        import vizdoom

        from vizdoom import gymnasium_wrapper  # noqa: F401
        env = gym.make("VizdoomBasic-v1", render_mode="rgb_array", frame_skip=4)
        env.reset(seed=0)
        env.close()
        return f"ViZDoom {vizdoom.__version__} · READY"
    except Exception as exc:
        return f"startup check pending · {type(exc).__name__}"


def _make_env(environment: str, seed: int):
    import gymnasium as gym
    from vizdoom import gymnasium_wrapper  # noqa: F401

    env = gym.make(environment, render_mode="rgb_array", frame_skip=4)
    env = gym.wrappers.TransformObservation(
        env,
        lambda observation: observation["screen"],
        observation_space=env.observation_space["screen"],
    )
    env = gym.wrappers.GrayscaleObservation(env, keep_dim=False)
    env = gym.wrappers.ResizeObservation(env, (84, 84))
    env = gym.wrappers.FrameStackObservation(env, stack_size=4)
    env.reset(seed=seed)
    return env


def _record(model, env, artifacts: Path, seed: int, task):
    observation, _ = env.reset(seed=seed)
    frames: list[np.ndarray] = []
    max_steps = int(task["max_steps"])
    for step in range(max_steps):
        frame = env.render()
        if frame is None and isinstance(observation, np.ndarray) and observation.ndim == 3:
            frame = observation
        if frame is not None and (step % 2 == 0 or step < 20):
            frames.append(np.asarray(frame))
        action, _ = model.predict(observation, deterministic=True)
        observation, _, terminated, truncated, _ = env.step(action)
        if terminated or truncated:
            break
    env.close()
    return save_gif(frames, artifacts / f"{task['key']}-learned-policy.gif", fps=18)


def run(key: str, budget: int, learning_rate: float, gamma: float, epsilon: float, seed: int, checkpoints: int | None = None):
    task = next(item for item in TASKS if item["key"] == key)
    environment = task["environment"]
    yield from train_sb3(
        root=ROOT,
        task=task,
        make_train_env=lambda: _make_env(environment, seed),
        make_eval_env=lambda: _make_env(environment, seed + 1_000),
        make_record_env=lambda: _make_env(environment, seed + 10_000),
        budget=budget,
        learning_rate=learning_rate,
        gamma=gamma,
        epsilon=epsilon,
        seed=seed,
        checkpoints=checkpoints,
        record_episode=lambda model, env, artifacts, record_seed: _record(model, env, artifacts, record_seed, task),
    )
